// Code generated by Prismic. DO NOT EDIT.

import BeliefsList from "./BeliefsList";
import CallToAction from "./CallToAction";
import ContactForm from "./ContactForm";
import ContentGrid from "./ContentGrid";
import EventList from "./EventList";
import Feature from "./Feature";
import ImagePoster from "./ImagePoster";
import InfoList from "./InfoList";
import MapEmbed from "./MapEmbed";
import PageHeader from "./PageHeader";
import RichText from "./RichText";
import TeamGrid from "./TeamGrid";

export const components = {
	beliefs_list: BeliefsList,
	call_to_action: CallToAction,
	contact_form: ContactForm,
	content_grid: ContentGrid,
	event_list: EventList,
	feature: Feature,
	image_poster: ImagePoster,
	info_list: InfoList,
	map_embed: MapEmbed,
	page_header: PageHeader,
	rich_text: RichText,
	team_grid: TeamGrid,
};
